
-- 1. Get best-selling product per store.
-- 1. Find customer who bought most expensive product.
-- 1. Get store with highest average sale value.
-- 1. Find category generating highest revenue.
-- 1. Find customers who bought the most expensive product.
-- 1. Get stores selling products above average price.
-- 1. Find products sold in all stores.
-- 1. Get customers who never purchased anything.
-- 1. Find stores with no sales.

-- 1. Rank sales within each store by quantity.
-- 1. Get top 3 sales per store.
-- 1. Calculate percentage contribution of each sale.
-- 1. Find difference between consecutive sales.
-- 1. Get lag/lead sales quantity.
-- 1. Use CTE to calculate daily revenue trends.
-- 1. Use CTE to find top category per city.
-- 1. Use multiple CTEs to calculate profit logic.
-- 1. Use recursive CTE for sequence.
-- 1. Use CTE to filter top 10% customers.
-- 1. Find customers contributing to 80% revenue.

-- 1. Get products with declining sales trend.
-- 1. Find stores with consistent growth.
-- 1. Identify peak sales month.
-- 1. Find repeat customers.
-- 1. Get average gap between purchases.
-- 1. Find most popular product per city.
-- 1. Calculate customer lifetime value.
-- 1. Find top 3 categories by revenue.
-- 1. Combine JOIN + CTE + WINDOW to rank customers globally.